# Generated by Django 4.1.3 on 2022-12-01 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='name',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.imagemodel'),
        ),
    ]
